owner: mentordosnerds
repo: upptime

sites:
  - name: Chatwoot
    url: https://messages.mentordosnerds.com.br

  - name: Wallos
    url: https://subscriptions.mentordosnerds.com.br

  - name: i-9.ai
    url: https://i-9.ai

  - name: transformandovidas.online
    url: https://transformandovidas.online

  - name: contacto.transformandovidas.online
    url: https://contacto.transformandovidas.online

  - name: Evolution API
    url: https://whatsapp.mentordosnerds.com.br
    headers:
      - "CF-Access-Client-Id: $CLOUDFLARE_CLIENT_ID"
      - "CF-Access-Client-Secret: $CLOUDFLARE_CLIENT_SECRET"

  - name: LiteLLM
    url: https://openapi.mentordosnerds.com.br
    headers:
      - "CF-Access-Client-Id: $CLOUDFLARE_CLIENT_ID"
      - "CF-Access-Client-Secret: $CLOUDFLARE_CLIENT_SECRET"

  - name: Traefik HTTP
    url: https://mentordosnerds.com.br
    port: 80
    check: "tcp-ping"

  - name: Traefik HTTPS
    url: https://mentordosnerds.com.br
    port: 443
    check: "tcp-ping"

status-website:
  theme: ocean
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
